AllCops:
  Exclude:
    - 'bin/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
